name: Build on Ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_client_certificate: ${{ secrets. CLIENT_CERTIFICATE }}
  TF_VAR_client_key: ${{ secrets.CLIENT_KEY }}
  TF_VAR_cluster_ca_certificate: ${{ secrets.CLUSTER_CA_CERTIFICATE }}
  TF_VAR_kubernetes_host: ${{ secrets.KUBERNETES_HOST }}
  TF_VAR_traefik_dashboard_auth: ${{ secrets.TRAEFIK_DASHBOARD_AUTH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up WireGuard
        uses: bengtfredh/setup-wireguard@v2
        with:
          # Endpoint in the HOST:PORT format
          endpoint: '${{ secrets.WG_ENDPOINT }}'
          # Public key of the endpoint
          endpoint_public_key: '${{ secrets.WG_PUBLICKEY }}'
          # Comma-separated list of IP addresses
          ips: '${{ secrets.WG_IPS }}'
          # Comma-separated list of netmasks
          allowed_ips: '${{ secrets.WG_ALLOWEDIPS }}'
          # Private key
          private_key: '${{ secrets.WG_PRIVATEKEY }}'
          # Preshared key
          #preshared_key: # optional
      - name: Check wg up
        run: ping -c 3 '${{ secrets.PING_TEST_IP }}'
      - name: Terraform Init
        working-directory: ./tf
        id: init
        run: terraform init -input=false
      - name: Terraform Apply
        working-directory: ./tf
        id: apply
        run: terraform apply -auto-approve -input=false
