name: Build on Ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up WireGuard
        uses: bengtfredh/setup-wireguard@v2
        with:
          # Endpoint in the HOST:PORT format
          endpoint: '${{ secrets.WG_ENDPOINT }}'
          # Public key of the endpoint
          endpoint_public_key: '${{ secrets.WG_PUBLICKEY }}'
          # Comma-separated list of IP addresses
          ips: '${{ secrets.WG_IPS }}'
          # Comma-separated list of netmasks
          allowed_ips: '${{ secrets.WG_ALLOWEDIPS }}'
          # Private key
          private_key: '${{ secrets.WG_PRIVATEKEY }}'
          # Preshared key
          #preshared_key: # optional
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        working-directory: ./tf
        id: init
        run: terraform init
      - name: Terraform Plan
        working-directory: ./tf
        id: plan
        run: terraform plan -no-color -out "planfile"
        # continue-on-error: false
      - name: Terraform Apply
        working-directory: ./tf
        id: apply
        run: apply -input=false "planfile"
        # continue-on-error: false
